#ifndef GRAPHICSBASE_H
#define GRAPHICSBASE_H

#include "CommonClass.h"

enum CustomizedGraphics{ GRAPHICS_ARROW, GRAPHICS_BASE, GRAPHICS_CURVE, GRAPHICS_DOMAIN, GRAPHICS_FLOW, GRAPHICS_EDGE,
                         GRAPHICS_METABOLITE, GRAPHICS_REACTION, GRAPHICS_ROUTER, GRAPHICS_VERTEX };

#endif // GRAPHICSBASE_H
